AWSTemplateFormatVersion: "2010-09-09"
Description: A CloudFormation template example
Parameters:
  MyProductDeploymentParameters: { Description: Secret Name, Type: String }
Resources:
 CrossAccountS3AccessRole:
  Type: AWS::IAM::Role
  Properties:
   RoleName: "MyCrossAccountRole"
   AssumeRolePolicyDocument:
    Version: "2012-10-17"
    Statement:
     - Effect: Allow
       Principal:
         AWS:
          Fn::Sub:
          - "{{resolve:secretsmanager:${inputParameter}:SecretString:PrincipalARN}}"
          - inputParameter: 
              Ref: MyProductDeploymentParameters
       Action: sts:AssumeRole
       Condition: 
         StringEquals:
           sts:ExternalId:
            Fn::Sub:
            - "{{resolve:secretsmanager:${inputParameter}:SecretString:ExternalID}}"
            - inputParameter: 
                Ref: MyProductDeploymentParameters
   Path: "/"
   Policies:
     - PolicyName: S3BucketAccess
       PolicyDocument:
         Version: "2012-10-17"
         Statement:
           - Effect: Allow
             Action:
               - s3:List*
             Resource: "some-example-resource"   
